language: php

sudo: false

php:
   # At time of writing, travis builds for these PHP versions fail
   # So for now let's just mark them as unsupported.
   #- 5.2
   #- 5.3
   - 5.4
   - 5.5
   - 5.6
   - 7.0
   #- hhvm

before_script:
   - composer install

script:
   - phpunit --configuration phpunit.xml
